# register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username": "niko",
    "email": "seller@gmail.com",
    "password":"123",
    "confirmPassword":"123",
    "role": "seller"
}

# Login
###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "seller@gmail.com",
    "password":"123"
}

#autentikasi
###
GET http://localhost:4000/api/auth/authenticated
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InNlbGxlciIsImlhdCI6MTcwNDM1OTgwNSwiZXhwIjoxNzA0MzYzNDA1fQ.DiJx8E4mf9tXtYQ-om6I4Wisaa0aiSFSUtLTb9Y20Qc

# Melihat daftar user
###
GET  http://localhost:4000/api/auth/users

# Tes
###
GET http://localhost:4000/

# Membuat produk
###
POST http://localhost:4000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InNlbGxlciIsImlhdCI6MTcwNDM1OTgwNSwiZXhwIjoxNzA0MzYzNDA1fQ.DiJx8E4mf9tXtYQ-om6I4Wisaa0aiSFSUtLTb9Y20Qc

{
    "name": "Makaroni Udang",
    "description": "Kerupuk makaroni yang berasal dari udang",
    "price": 3000,
    "stock": 10
}

# Melihat daftar produk
###
GET http://localhost:4000/api/products?page=1&limit=10

# Checkout
###
POST http://localhost:4000/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InNlbGxlciIsImlhdCI6MTcwNDM1OTgwNSwiZXhwIjoxNzA0MzYzNDA1fQ.DiJx8E4mf9tXtYQ-om6I4Wisaa0aiSFSUtLTb9Y20Qc

{
    "productId": 2,
    "quantity": 1
}

###
GET http://localhost:4000/api/order?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InNlbGxlciIsImlhdCI6MTcwNDMyMjM3NSwiZXhwIjoxNzA0MzI1OTc1fQ.tlKEo9O37yHKi7Ya24sqYlfyRJascmEQjG4ShYn_WnM
